### ISSUE TITLE
[Template] Transaction template

### ISSUE THREAD

**Issue by mateuszsinilo** [modularcloud/explorer#13]
# Description

# Images

# Component Type

- [ ] Atom
- [ ] Molecule
- [ ] Organism
- [x] Template
- [ ] Page
- [ ] Other

# Styles

## Transaction template
<img width="941" alt="Screen Shot 2023-01-06 at 18 18 10" src="https://user-images.githubusercontent.com/93646100/211068977-ca40aaec-026a-4d34-97e1-79edaad8bb9e.png">

- atom H2: https://github.com/modularcloud/explorer/issues/4
- organism transaction block: https://github.com/modularcloud/explorer/issues/12

# Implementation

**Comment by lzrscg** [comment]
@mateuszsinilo can we take out the ... on the left? just trying to simplify this component a bit for v1

**Comment by lzrscg** [comment]
meant to post that here: https://github.com/modularcloud/explorer/issues/11
