### ISSUE TITLE
ContractVerification (proteus testnet) - unsuccessful fetching

### ISSUE THREAD

**Issue by mhstom** [modularcloud/explorer#134]
# Description
I deployed an erc20 contract to proteus testnet successfully https://proteus.nautscan.com/proteus/search/0x0f2035E7Da070A3b33eD3C6BD8350c116B72D294 and tried to verify the contract. It shows 
```
Verification Failed Resource
missing; unsuccessful fetching:
@openzeppelin/contracts/token/ER
C20/ERC20.sol
```

# Screenshot / Video
![Screen Shot 2023-08-24 at 10 46 08 AM](https://github.com/modularcloud/explorer/assets/112976086/3dc0c2be-9561-4973-951d-a3ead87d2f18)

# URL / Steps to reproduce
contact code (i used .txt to upload here as github doesn't support json)
[mcerc20.txt](https://github.com/modularcloud/explorer/files/12432123/mcerc20.txt)

metadata.json (i used .txt to upload here as github doesn't support json)
[ERC20Token_metadata.txt](https://github.com/modularcloud/explorer/files/12432114/ERC20Token_metadata.txt)

# Expected behavior
It should be verified successfully.

# Notes

**Comment by Aswanth-c** [comment]
![Screenshot 2023-09-05 at 3 56 26 PM](https://github.com/modularcloud/explorer/assets/57211637/48c8c845-69ae-4e81-8275-ffea3b795e0b)
weird I just uploaded the same data and I got it verified successfully
