### ISSUE TITLE
Search Modal

### ISSUE THREAD

**Issue by lzrscg** [modularcloud/explorer#159]
# Introduction
To help motivate this, I will first share some user stories:

As a user, I want to be able to easily search for content on a the same blockchain I am already viewing.
As a user, I want to be able to easily search for content on a different blockchain than I am already viewing.

In order to make this **easy**, we want to minimize the number of interactions a user has to take, while also making both of these tasks (searching the same or different chain) intuitive.

Minimum number of interactions for searching the same chain:
1. User selects search box (or uses hotkey)
2. User types search query
3. User presses search button (or users hotkey)

Minimum number of interactions for switching chains and searching:
1. User engages search area (or uses hotkey)
2. User selects new chain (this may be a complex interaction, depending on how many chains. Since we are expecting a large number of chains in the future, we need to design with this in mind. Therefore, a user may need to type the name of the chain they want to use instead of clicking on a dropdown)
3. User types search query
4. User presses search button (or users hotkey)

The question is how do we intuitively combine these into the same flow.

# Same chain flow
1. User opens modal
![image](https://github.com/modularcloud/explorer/assets/84213303/cd3cf0fc-06a0-4ff5-b35f-84f128508167)
2. User types search (it auto-selects the default chain)
![image](https://github.com/modularcloud/explorer/assets/84213303/d1830c40-ee98-4ae9-aca0-16f369376fa6)
3. User presses enter or clicks option

# Different chain flow
1. User opens modal
![image](https://github.com/modularcloud/explorer/assets/84213303/cd3cf0fc-06a0-4ff5-b35f-84f128508167)
2. User selects chain (with arrow keys and enter, or clicking) OR by searching, which filters out non-matches
![image](https://github.com/modularcloud/explorer/assets/84213303/0d6104db-3b08-49ff-9ce0-ffd73922db6d)
Upon selection:
![image](https://github.com/modularcloud/explorer/assets/84213303/7d8c06b5-8798-47c2-b34c-fcc49da96dfb)
3. User types search
![image](https://github.com/modularcloud/explorer/assets/84213303/d1830c40-ee98-4ae9-aca0-16f369376fa6)
3. User presses enter or clicks option

# Implementation Details
## What types are available to search on a chain
We will provide a library for this. You pass in a chain's slug, and get the types available to search. This library will also provide a function that validates if the query matches the type. For example "123" does not match a transaction, so we do not need to display this an option for the user.

TODO: define ordering logic, if multiple types match the same query.

## Determining if a user is searching for a chain or for block, transaction, etc.?
If the search matches a chain, then we assume it is a chain.

## No matches found for a query
TODO: We need to create a screen for that.

## Matching a query to a chain
I don't have a strong opinion on how we should preform matching exactly. Perhaps we should do some sort of fuzzy matching, or we could use regex. With that said, there is some complex logic involved.

Imagine a brand "Celestia" with two chains, with names "Arabica" and "Mocha".
In this case, if the user types "cel" and it matches with the brand "Celestia", then all networks within Celestia are included.

However, if the user searches "ara", this does not match with "Celestia" or "Mocha", but does match with "Arabica". In which case, "Mocha" would no longer be displayed—but "Arabica" would still be under the "Celestia" section.

Lastly, if the user typed "abc", this would match none of them and the entire section would be eliminated.

Here is a potential implementation:
Imagine the list of chains like this
```javascript
[
   {
      chainBrand: "Celestia",
      chainName: "Mocha",
      // ...
   },
   {
      chainBrand: "Celestia",
      chainName: "Arabica",
      // ...
   }
]
```
You could filter out chains with this logic:
```javascript
list.filter((chain) => `${chain.chainBrand.toLowerCase()} ${chain.chainName.toLowerCase()}`.indexOf(usersQueryString.toLowerCase()) !== -1)
```
Perhaps it might also be good to remove whitespace, but either way the purpose is to match the users input to a string containing the name and brand of the chain. Then, you can just render UI based off of this filtered list (you maybe need to regroup them, depending on how the data needs to be structured for the UI.

We will need to move this to a backend service once the list of chains gets longer. But for now, everything can be done client side.

## Keyboard navigation logic
In the grid view (selecting chains), up and down goes between chains inside of a box. If you are at the bottom of a box, and there is a box below, then pressing down will take you to the first chain on the box bellow.

If you are at the top of the box and there is a box above, pressing up will take you to the bottom chain of the box above.

If you there is a box to the right, pressing right will take you to the top chain in the box to the right. Same with pressing left, if there is a chain to he left.

Enter always selects chain and moves on to the next screen.

Using keyboard navigation will change the default chain, so the default text says "Search [currently selected chain] or Switch Chains". In other words, the user does not strictly need to press enter or the Select button.

Clicking on a chain selects it and goes to the next string.

TODO: add mouse hover style

In the list view, you can only navigate up and down.

**Comment by Fredkiss3** [comment]
I don't understand this sentence : 

> If the existing selection is not filtered out by the search, then it should remain selected. If the selection is no longer an option, then the very first option will be selected.

**Comment by Fredkiss3** [comment]
done in  #162
