### ISSUE TITLE
[Molecule] Footer

### ISSUE THREAD

**Issue by mateuszsinilo** [modularcloud/explorer#19]
# Description

# Images

# Component Type

- [ ] Atom
- [x] Molecule
- [ ] Organism
- [ ] Page
- [ ] Other

# Styles
Desktop
![copyrights](https://user-images.githubusercontent.com/93646100/211159829-2cfdddc5-3c0c-4117-bc37-88f1782a831d.jpg)

## Footer

display: flex
height: 100px
width: 100%
borderTop: 1px solid D9D9D9
alignItems: center
justifyContent: space-between
paddingX: 60px

Tablets and mobiles (1023px and below)
![copyrights (1)](https://user-images.githubusercontent.com/93646100/211163549-cb20c11c-5b39-49ab-9771-755d8d2763c3.jpg)

- box 
width: 100%
backgroundColor: 'EEEEEE'
height: 240px
display: flex
flexDirection: column
justifyContent: center
alignItems: center

flex for labels: gridGap: 24px
padding: 42px 
and then we put @ copyrights

# Implementation

**Comment by lzrscg** [comment]
how much space is between the links (About Us, Terms, etc.) @mateuszsinilo?
