### ISSUE TITLE
Blob namespace mismatch on blob and msg pages

### ISSUE THREAD

**Issue by mhstom** [modularcloud/explorer#259]
1. this is the transaction message https://explorer.modular.cloud/celestia-mainnet/transactions/e6181b6629ecc76e1f592df6d87c4551b13aeef3c5b82e20b7831f19f6d671f9/messages/0
2. this is the transaction blob page https://explorer.modular.cloud/celestia-mainnet/transactions/e6181b6629ecc76e1f592df6d87c4551b13aeef3c5b82e20b7831f19f6d671f9/blobs/0
3. The namespace should match

**Comment by lzrscg** [comment]
migrated to linear
