### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by mateuszsinilo** [modularcloud/explorer#32]
# Description

# Design

![Colour palette](https://user-images.githubusercontent.com/93646100/217705877-1f1cfe3e-e400-4372-a818-7564af8831eb.png)
[View on Figma](https://www.figma.com/file/JwErDZu5OhBpzSKgLRhDPw/Client-%2F-Celestia-Scan?node-id=1291%3A16483&t=9Yb7Vs6jOHS9i7h4-0)

```
export const Colors = {
        brandMain: '',
        brandMain: '',
        brandMain: '',
        brandMain: '',
        brandMain: '',
        brandMain: '',
        brandMain: '',
}
```

# Subcomponents

# Implementation notes

**Comment by lzrscg** [comment]
done!
