### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by mateuszsinilo** [modularcloud/explorer#33]
# Description

# Design

**General idea:** 
On OS system we use SF Compact font: [SF Comptact](https://developer.apple.com/fonts/)
On different such as Android, Windows we Inter font: [Inter](https://fonts.google.com/specimen/Inter)

```
export const Fonts = {
      macOS: 'SF Compact',
      non-macOS: 'Inter'
}
```

# Subcomponents

# Implementation notes

**Comment by lzrscg** [comment]
done!
