### ISSUE TITLE
Feature Request: ability to search by namespace ID

### ISSUE THREAD

**Issue by rootulp** [modularcloud/explorer#56]
I would like the ability to query https://explorer.modular.cloud/ by a Celestia namespace ID. The explorer could have a dedicated page for namespace ID that shows:
- recent transactions that paid for the inclusion of a blob at this namespace ID
- how many times has the namespace ID been published to in the last day, week, year, since genesis

**Comment by lzrscg** [comment]
great idea! will prioritize this 🙏
