### ISSUE TITLE
Preserve view on refresh

### ISSUE THREAD

**Issue by lzrscg** [modularcloud/explorer#66]
# Description
When the table or card view is selected and the page is refreshed, then it reverts to the default view.

# Screenshot / Video

# URL / Steps to reproduce
1. Go to https://triton.nautscan.com/triton/account/0x539187da15c3daae90302ae97ff224c663a95ac3/transactions
2. Open card view
3. Refresh page

# Expected behavior

# Notes

**Comment by Aswanth-c** [comment]
I would appreciate your thoughts on tackling the issue.

First way:
When a user selects a view, we can update the URL with a parameter representing the user's selection. Then, when the page is reloaded, we can read the parameter from the URL and display the appropriate view.

Pros:
People can share the URL with their desired view 
Cons:
When the user reloads the page or comes back later, the first view  will always be a  
table view
not a con, The Url will have parameters.

Second way:
Storing the data in cookies 
Pros:
When the user reloads the page or returns later, we can check the cookie to determine which view they selected last time and show it by default.

Cons:
The user cannot share the selected view with someone.
