### ISSUE TITLE
too short search bar

### ISSUE THREAD

**Issue by mateuszsinilo** [modularcloud/explorer#68]
# Description
Search bar on the block page is too shirt, his width should be 448px, now it's 308px, so it cuts off the placeholder label
# Screenshot / Video
<img width="1440" alt="Screen Shot 2023-05-04 at 23 29 51" src="https://user-images.githubusercontent.com/93646100/236334276-ed24299a-aaa2-46ed-a899-2f7837db4057.png">

# URL / Steps to reproduce
1. Go to https://explorer.modular.cloud/celestia-mocha/search/4224
2. Make search bar wider

# Expected behavior
Search bar on the desktop should have 448px, and the smaller ones desktop such as 1024px it should be 368px, either way it's too smaller

# Notes

**Comment by lzrscg** [comment]
@mateuszsinilo can you share the width at each breakpoint?

**Comment by mateuszsinilo** [comment]
> @mateuszsinilo can you share the width at each breakpoint?

**Breakpoints:**
1728 - 448px
1440 - 448px
1024 - 368px
On smaller resolutions we have modal, it looks quite better, but if you want improvements, it'd be
768 - 576px
640 - 512px
375 - 343px
