### ISSUE TITLE
[UI] Context menu and align three dots

### ISSUE THREAD

**Issue by mateuszsinilo** [modularcloud/explorer#76]
# Description
We have a feature on table transaction that by clicking three dots we show a context menu.

link to Figma: https://www.figma.com/file/WY5HXfjno1GhLDG9JqxNTV/SIMPLE-VERSION---MVP-(15.02)?type=design&node-id=788-16381&t=BvFyIR6C9XGxepQO-0

Also align three dots inside the table. They should be centered. 

# Screenshot / Video
Context menu: 
<img width="993" alt="Screen Shot 2023-05-11 at 01 06 16" src="https://github.com/modularcloud/explorer/assets/93646100/5175b9a1-460e-40f6-a01b-f897cad9ee63">

Not-aligned dots:
<img width="987" alt="Screen Shot 2023-05-06 at 23 28 46" src="https://user-images.githubusercontent.com/93646100/236647455-7a2c626f-c1b4-4ec8-a964-c0359eee0228.png">

# URL / Steps to reproduce
**Context menu:**

**1) The whole box**
```
border-radius: 12px;
background: #FFFFFF;
flex-direction: 'column';
border: 1px solid rgba(42, 43, 46, 0.1);
box-shadow: 0px 16px 32px rgba(42, 43, 46, 0.16), 0px 4px 8px rgba(42, 43, 46, 0.07), 0px 0px 4px rgba(42, 43, 46, 0.04);
```
**2) Inside that box we have rectangles with each functionality such as copy, preview, and so on**
```
height: 40px;
width: 100%
justify-content: space-between
padding: 12px
bgColor: hover ? 'rgba(8, 6, 21, 0.02)' : 'transparent'
```
**3) Inside rectangle we have two labels, first for function, second for shortcuts, both as simple fonts**

function label:
```
color:' #2A2B2E'
font-weight: '500'
font-size: '13px'
```
shortcut label: 
```
color:' #80838D'
font-weight: '400'
font-size: '12px'
```

**3) between each box we have simple line**
```border: 1px solid rgba(8, 6, 21, 0.06);```

# Expected behavior
The context menu should be opened by clicking three dots and hidden by clicking anywhere on a page. Additionally, three dots should be aligned center

# Notes

**Comment by lzrscg** [comment]
Can you add more details about the context menu here? @mateuszsinilo

**Comment by lzrscg** [comment]
The options for the context menu are (no icons needed, no functionality needed on click):
- Open
- Preview
- Copy

**Comment by mateuszsinilo** [comment]
**Context menu:**
link to Figma: https://www.figma.com/file/WY5HXfjno1GhLDG9JqxNTV/SIMPLE-VERSION---MVP-(15.02)?type=design&node-id=788-16381&t=BvFyIR6C9XGxepQO-0

<img width="993" alt="Screen Shot 2023-05-11 at 01 06 16" src="https://github.com/modularcloud/explorer/assets/93646100/5175b9a1-460e-40f6-a01b-f897cad9ee63">

Steps to implement:

**1) The whole box**
```
border-radius: 12px;
background: #FFFFFF;
flex-direction: 'column';
border: 1px solid rgba(42, 43, 46, 0.1);
box-shadow: 0px 16px 32px rgba(42, 43, 46, 0.16), 0px 4px 8px rgba(42, 43, 46, 0.07), 0px 0px 4px rgba(42, 43, 46, 0.04);
```
**2) Inside that box we have rectangles with each functionality such as copy, preview, and so on**
```
height: 40px;
width: 100%
justify-content: space-between
padding: 12px
bgColor: hover ? 'rgba(8, 6, 21, 0.02)' : 'transparent'
```
**3) Inside rectangle we have two labels, first for function, second for shortcuts, both as simple fonts with the same size**

function label:
```
color:' #2A2B2E'
font-weight: '500'
font-size: '13px'
```
shortcut label: 
```
color:' #80838D'
font-weight: '400'
```

**3) between each box we have simple line**
```border: 1px solid rgba(8, 6, 21, 0.06);```

**Comment by lzrscg** [comment]
@mateuszsinilo can you edit the original issue to have all the information? we want to make this very easy for people to understand

also can you try to make the hotkey labels smaller?

**Comment by mateuszsinilo** [comment]
> @mateuszsinilo can you edit the original issue to have all the information? we want to make this very easy for people to understand
> 
> also can you try to make the hotkey labels smaller?

yes, I'm editing, and you're right, we can make a shortcut label smaller, I recommend to make it 12px, below that fonts are hard to read

**Comment by lzrscg** [comment]
sounds good!

*LZRS*
*CEO, Modular Cloud*
celestiascan.com
