### ISSUE TITLE
[UI] Mobile - close icon of toggled sidebar

### ISSUE THREAD

**Issue by mateuszsinilo** [modularcloud/explorer#78]
# Description
The close icon of toggled sidebar is overlaying with transaction address, when there's no network logo. When the network logo is there, for example Celestia, the whole thing looks good. 

# Screenshot / Video
<img width="401" alt="Screen Shot 2023-05-06 at 23 54 16" src="https://user-images.githubusercontent.com/93646100/236648390-773a3f7a-27d8-44c4-861d-79ce2e27ee38.png">

# URL / Steps to reproduce
1. Go to https://dymscan.com/hub/transaction/7B77A00D91AF64E8C6B9D22124E5C185CF52729F35DBDE87343EA04876093122 and open on mobile
2. Click sidebar icon

# Expected behavior
<img width="401" alt="Screen Shot 2023-05-06 at 23 54 27" src="https://user-images.githubusercontent.com/93646100/236648394-034b1e17-d138-4e6d-90f7-48137f73cebf.png">

# Notes

**Comment by lzrscg** [comment]
this will be fixed soon once we add logos back into into the sidebar of all the explorers. I will keep this open for now, but I don't plan on fixing this

**Comment by lzrscg** [comment]
fixed
