### ISSUE TITLE
[Theme] Globals

### ISSUE THREAD

**Issue by mateuszsinilo** [modularcloud/explorer#8]
# Description
These global variables will allow us to use a theme to make the development experience better.

# Styles

## Colors

![COLORS](https://user-images.githubusercontent.com/93646100/209983156-73c5b9cc-5ad4-4976-a562-e2d459f3d581.jpg)

```
colors: {
      lightBlack: '#4a4949',
      beige: '#a8a2a2',
      grayMain: {
        light: '#eeeeee',
        medium: '#d9d9d9',
        dark: '#7c7c7c',
      },
      grayBG: {
        light: '#f9f9f9',
        hover: '#f2f2f2',
      },
      green: {
        light: '#eef9f5',
        hover: '#2db993',
          },
      red: {
        light: '#ffecf3',
        hover: '#e74d4d',
          },
    }
```

## Screens

```
screens: {
      'mobile': '479px', 
      'tablets': '480 - 1023px',
      'desktop': '1024 - 1728px',
    }
```

## Font

```
fontFamily: {
      sans: ['Inter', 'sans-serif'],
    },
```

import('https://fonts.google.com/specimen/Inter')

# Implementation
We will create a [Tailwind theme](https://tailwindcss.com/docs/theme).

**Comment by lzrscg** [comment]
@mateuszsinilo can you include an image of the color palette?

**Comment by mateuszsinilo** [comment]
> @mateuszsinilo can you include an image of the color palette?

added, @lzrscg
