### ISSUE TITLE
[suggestion] If there's no value in search bar then it shouldn't work

### ISSUE THREAD

**Issue by mateuszsinilo** [modularcloud/explorer#80]
# Description
The search bar is working even with empty value, my little suggestion is that it shouldn't be working, when nothing in typed. And we can add another state to the search bar with red stroke. 

# Screenshot / Video

# URL / Steps to reproduce

# Expected behavior
<img width="750" alt="Screen Shot 2023-05-07 at 15 51 15" src="https://user-images.githubusercontent.com/93646100/236684015-fbf3b2a3-4170-46dc-ba88-81abab8f877a.png">

# Notes

**Comment by lzrscg** [comment]
Great point!

**Comment by lzrscg** [comment]
I think we can just have it take no action, it doesn't need to give an error message

**Comment by Aswanth-c** [comment]
> I think we can just have it take no action, it doesn't need to give an error message

+1
Easy fix 
I have created a pull request for this 
https://github.com/modularcloud/explorer/pull/93
