### ISSUE TITLE
Events on Polygon look bad on smaller resolutions

### ISSUE THREAD

**Issue by mateuszsinilo** [modularcloud/explorer#82]
# Description
The events on Polygon have too many values, so there's not enough space between them. 

Here also happens the same situation, as I previously described in [this issues](https://github.com/modularcloud/explorer/issues/74). You cannot see the values of certain events in compact view, such as topics, data, long index etc.

# Screenshot / Video
Compact view:
<img width="787" alt="Screen Shot 2023-05-07 at 17 02 27" src="https://user-images.githubusercontent.com/93646100/236685565-11477499-05db-4ebe-a264-e3b71cd65187.png">
<img width="350" alt="236685566-fad916b1-f2fc-4b83-8104-5671df5af9c5" src="https://user-images.githubusercontent.com/93646100/236685943-33c3e008-b481-4029-b8be-fa759ae9bfe5.png">

Smaller things with card view: 
<img width="342" alt="Screen Shot 2023-05-07 at 17 09 22" src="https://user-images.githubusercontent.com/93646100/236685855-a4c370ce-4a5f-4382-879c-b06ef48829a3.png">

# URL / Steps to reproduce
1. Go to https://explorer.modular.cloud/caldera-polygon/transaction/0x02c846bbe7bf608839c5af9e234a9a955a7c643eaf92a9deb73cd45afd022e7a

# Expected behavior
There should be more spaces between values

# Notes

**Comment by lzrscg** [comment]
yes, we should set a max length on some of these values.
