### ISSUE TITLE
[Mobile] Transaction block icon looks same as card view icon

### ISSUE THREAD

**Issue by mateuszsinilo** [modularcloud/explorer#83]
# Description
On the smaller resolutions, we have transaction icon that looks same as card view icon, it's confusing. 

# Screenshot / Video
<img width="354" alt="236686168-bde1c647-a3e1-4f0f-ab43-7971460d84c0" src="https://user-images.githubusercontent.com/93646100/236686230-9847ef48-d8df-4c8f-907a-46f03d10fceb.png">

# URL / Steps to reproduce
1. Go to https://explorer.modular.cloud/caldera-polygon/transaction/0x02c846bbe7bf608839c5af9e234a9a955a7c643eaf92a9deb73cd45afd022e7a

# Expected behavior
1) We can remove that icon or
2) Change this icon

# Notes

**Comment by lzrscg** [comment]
Let's remove it

**Comment by lzrscg** [comment]
temporarily closing this because I took out the topbar for now
