### ISSUE TITLE
Clicking some buttons on homepage sometime don't response

### ISSUE THREAD

**Issue by mhstom** [modularcloud/explorer#84]
# Description
When I am on the homepage https://triton.nautscan.com/, sometime when clicking "View All" of the Latest Blocks table or clicking some of the block numbers in the Latest Blocks table, nothing happens. 

# Screenshot / Video
N/A
# URL / Steps to reproduce
It's not 100% reproducible. I notice that it happens more frequent when:
 1. go to the home page
 2. you will see all blocks have “a few seconds ago”
 3. wait for them to change to “a minute ago”
 4. clicking some blocks number or view all don’t have response

The blocks numbers that don't have response are very random.

# Expected behavior
Should navigate me to the corresponding block or view all page

# Notes

**Comment by lzrscg** [comment]
this has been fixed
