### ISSUE TITLE
Use edge runtime for rendering pages

### ISSUE THREAD

**Issue by lzrscg** [modularcloud/explorer#95]
We should not be doing anything that prohibits edge in the app dir. Only our api should contain a NodeJS dependency, and we will eventually move that to AWS in production.

https://nextjs.org/docs/app/building-your-application/rendering/edge-and-nodejs-runtimes

**Comment by pynchmeister** [comment]
I am getting a slightly different error on branch ```ft/edgeRuntime```. I think this thread is applicable:

https://github.com/code-hike/lighter/issues/19

**Comment by lzrscg** [comment]
yes! exactly, I actually posted that thread :) thanks for taking a look

**Comment by lzrscg** [comment]
oh wait! no I didn't I thought you linked to mine
https://github.com/code-hike/bright/issues/20#issuecomment-1605383887

**Comment by lzrscg** [comment]
Yes @pynchmeister could you find a way to replicate this so we can share with the codehike folks?

Maybe in a codesandbox or just a standalone example inside our monorepo.

**Comment by pynchmeister** [comment]
Sure thing. Here is a direct link: https://codesandbox.io/p/sandbox/bitter-cloud-lk9r5z?file=%2Fapp%2Fpage.tsx%3A29%2C31

And I also left one in the issue you linked in their repository as well.
