### ISSUE TITLE
Different value of block on right panel and sidebar

### ISSUE THREAD

**Issue by mateuszsinilo** [modularcloud/explorer#98]
# Description
The values that are on block page shows network, type and execution, but on smaller resolutions we don't have right panel, instead we have toggled sidebar, and when you click on that, it doesn't show the same values, such as network, type and execution, it repeats the block info that you see in the card

# Screenshot / Video
Desktop:
<img width="449" alt="Screen Shot 2023-05-27 at 01 25 56" src="https://github.com/modularcloud/explorer/assets/93646100/d5f7c9c4-8fc4-4d5c-92d0-e53b61fe6341">
Mobile / tablets:
<img width="395" alt="Screen Shot 2023-05-27 at 01 26 23" src="https://github.com/modularcloud/explorer/assets/93646100/e0d6a36a-3642-47b0-af27-697df3fd678e">

# URL / Steps to reproduce
1. Go to https://explorer.modular.cloud/celestia-mocha/search/24552
2. Check right panel and then decrease resolution or check on your phone the sidebar

# Expected behavior
Both right panel and sidebar should display same values

# Notes

**Comment by lzrscg** [comment]
This is expected behavior. On the overview, the idea is to have network information on the sidebar.

However, when you get into the table/card view of associated entities, you want to see the original entity's information. Does that make sense? Otherwise, when we provide an overview, the information would be in the main section AND the sidebar.

**Comment by mateuszsinilo** [comment]
> This is expected behavior. On the overview, the idea is to have network information on the sidebar.
> 
> However, when you get into the table/card view of associated entities, you want to see the original entity's information. Does that make sense? Otherwise, when we provide an overview, the information would be in the main section AND the sidebar.

I understand, but it repeats the same info that you have on the card

**Comment by lzrscg** [comment]
Makes sense!
